### ISSUE TITLE
MTLCompilerService crash upon startup, slow performance and missing effects

### ISSUE THREAD

**Issue by themacintoshnerd** [xemu-project/xemu#1466]
### Title

https://xemu.app/titles/4d530064/#Halo-2

MTLCompilerService crash upon startup, slow performance and missing effects 

### Bug Description

When launching Halo 2 "MTLCompilerService" on macOS crashes. What follows is a black screen followed by poor performance (8 FPS in the Menu, wildly variable in game) and many broken effects. Including but likely not limited to:

- loss of blue tint on the menu screen
- hud is broken (letters work as do button prompts all other effects are MIA)
- clear hands and legs on the view model (a holographic effect almost)

This is just what I encountered while testing. 

### Expected Behavior

I'd expect preformance to be similar to Halo CE (which I can run much better than I can 2 all testing here was done at 1x res, I tend to play CE at 3x res on this same machine) 

Menu should have a blue tint to it

Hud should have a cross hair, radar and shield status borders around the grenade indicators

Master Chiefs hands should be solid. 

Actual Behavior
![Screenshot 2023-06-28 at 6 37 40 pm](https://github.com/xemu-project/xemu/assets/32601031/40b1765e-fa38-4020-94cc-12f52cad7fe0)

Expected Behavior
![Screenshot 2023-06-28 at 6 56 53 pm](https://github.com/xemu-project/xemu/assets/32601031/5c855ed5-bed1-4413-9e5f-8b57c961eb2a)

Actual Behavior
![Screenshot 2023-06-28 at 6 30 34 pm](https://github.com/xemu-project/xemu/assets/32601031/ab2f26a0-1ca4-4643-84c2-9b0c38f62eb5)

Expected 
![Screenshot 2023-06-28 at 6 54 21 pm](https://github.com/xemu-project/xemu/assets/32601031/800a2cd5-8d98-402c-baa7-e1d4df58d6f5)
Behavior

### xemu Version

Version:      0.7.96
Branch:       master
Commit:       0ee7502c23b3c7c964c5295ff283284bfc1526d2
Date:         Sun Jun 18 08:03:32 UTC 2023

### System Information

OS: macOS 14.0 Sonoma DP2
SoC: Apple M2 (10 Core GPU Variant)
Driver: 4.1 Metal - 86
Shader: 4.10

### Additional Context

[mtl_xemu_crash.txt](https://github.com/xemu-project/xemu/files/11900554/mtl_xemu_crash.txt)

Willing to test further if needed. 

Lovely little project btw thanks for y'all's hard work :)

**Comment by mborgerson** [comment]
Thanks for the bug report.

* Regarding the visual issues you're seeing, they are already mentioned here: #524 
* Regarding performance, it is expected for now.
* Regarding the 'MTLCompilerService' crash, have you restarted your system lately? I have had issues after updates on macOS that were resolved by a restart.

In the future, please try to search for previous issues before filing, and when filing a new issue please try to narrow the issue report to a singular problem, so the issue can be more easily tracked and resolved. If you need to create multiple issues, that is okay.

**Comment by themacintoshnerd** [comment]
I see, should I close this issue and make one specifically for the  MTLCompilerService issue?

A restart also didn't fix the issue fwiw

![Screenshot 2023-06-28 at 7 28 45 pm](https://github.com/xemu-project/xemu/assets/32601031/0c1e52e8-c31f-40eb-a7d9-83f8f7e84afe)

**Comment by mborgerson** [comment]
> I see, should I close this issue and make one specifically for the MTLCompilerService issue?

Let's simply make this issue only about the MTLCompilerService issue for now

> A restart also didn't fix the issue fwiw

Thanks for checking
