### ISSUE TITLE
Dinosaur Hunting - broken water environment mapping (was Fog, dirt particles, and some water appear black)

### ISSUE THREAD

**Issue by ButtercupKitten** [xemu-project/xemu#1622]
### Title

https://xemu.app/titles/4d530069/#Dinosaur-Hunting-Ushinawareta-Daichi

### Bug Description

Fog effects appear black causing some sections with heavy fog use to be nearly unplayable. Some water effects also appear black and so do dirt particles.
![image](https://github.com/xemu-project/xemu/assets/165239401/fa94efba-085a-4d37-ae14-c2731ae3ae59)
![image](https://github.com/xemu-project/xemu/assets/165239401/8743a5e8-79a0-42a4-8293-10b1e32d78aa)
![image](https://github.com/xemu-project/xemu/assets/165239401/462f7e41-1b12-4664-ad84-e107fa6c6222)
![image](https://github.com/xemu-project/xemu/assets/165239401/f6501d31-75b1-4c67-b3f4-f52eba7b3050)

### Expected Behavior

Fog and water are not supposed to appear pitch black and neither is dust
![image](https://github.com/xemu-project/xemu/assets/165239401/4115dfb8-541d-4ec6-ac44-3602d42112a9)
![image](https://github.com/xemu-project/xemu/assets/165239401/ea8f3079-f89a-424c-8a80-329177576999)

### xemu Version

0.7.120

### System Information

CPU:          Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
OS Platform:  Windows
OS Version:    22H2
Manufacturer: NVIDIA Corporation
GPU Model:    NVIDIA GeForce RTX 3060/PCIe/SSE2
Driver:       4.0.0 NVIDIA 551.86
Shader:       4.00 NVIDIA via Cg compiler

**Comment by Triticum0** [comment]
~~Test with https://github.com/xemu-project/xemu/pull/1780 hopefully should fix the issue~~ Has no affect

**Comment by Triticum0** [comment]
Here a renderdoc https://drive.google.com/file/d/1vfBnTYfvfEvf2lHBU886P7aI-E_u4TIe/view?usp=sharing

**Comment by Triticum0** [comment]
Here a trace

[xemu.zip](https://github.com/user-attachments/files/22414947/xemu.zip)

**Comment by abaire** [comment]
That trace looks very similar to #2384, when rendering the water it is using an unbound texture sampler. That said, it is not the same problem, as #2384 has an unbound sampler in level 2, whereas `DOT_REFLECT_SPECULAR` is only available in stage 3.

Unfortunately the RenderDoc cap was made from a build that doesn't have my debug augmentation that counts draws, making it a bit hard to correlate the PGRAPH trace with the capture. Luckily it looks like the vertex shader is unique, so I am fairly certain that EID 30100 correlates to draw 267 in the log.

`nv2a_pgraph_method 0: 0x97 -> NV097_SET_SHADER_STAGE_PROGRAM<0x1e70> (0x64621 {0:2D_PROJECTIVE, 1:DOT_PRODUCT, 2:DOT_PRODUCT, 3:DOT_REFLECT_SPECULAR})` indicates that texture sampler 3 should use `PS_TEXTUREMODES_DOT_RFLCT_SPEC` (it does, according to the shader code) and suggests that something may be wrong with the way xemu implements that mode.

We don't have any PGRAPH tests for that mode either, so I'm not sure how well tested it is. We'll need to write some tests to verify proper behavior, then figure out what's going wrong here.

**Comment by abaire** [comment]
The missing texture might be a red herring/RenderDoc issue.

I see from the trace that a texture is bound to unit 3 and looking at the raw commands in RDC I see that EID 30115 binds a texture to GL_TEXTURE3. Something is still wrong, however, since it doesn't show up as bound in the fragment shader pipeline view. In fact, this texture is the output of the draws around EID 29487 and above, where it's building up an environment map.

EID 29643 binds the rendered environment texture, but looking at the state just a few events later, e.g., 29646, lists the texture as unbound.

**Comment by abaire** [comment]
Running the pgraph test for `PS_TEXTUREMODES_DOT_RFLCT_SPEC` I do not see the same issue with the env map texture being unbound, so it seems plausible that that is the real issue here. 

The test manually provides the environment texture whereas the game renders it, so that may be a contributing factor.

**Comment by abaire** [comment]
Looking more closely, the env texture is bound as `GL_TEXTURE_2D` but `PS_TEXTUREMODES_DOT_RFLCT_SPEC` requires a cubemap or 3d texture, in this case it's using a `samplerCube` to attempt to read which is why it shows up as unbound.

Interestingly, it looks like the texture is explicitly configured as 2D:
```
nv2a_pgraph_method 0: 0x97 -> NV097_SET_TEXTURE_OFFSET[3]<0x1bc0> (0x00D45000 => 13914112)
nv2a_pgraph_method 0: 0x97 -> NV097_SET_TEXTURE_FORMAT[3]<0x1bc4> (0x8910629 {DMA_A, BORDER_SOURCE_COLOR, SZ_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:512, BaseSizeV:256, BaseSizeP:1})
```

**Comment by abaire** [comment]
That seems to explain the difference. On hardware, sending a 2d texture in place of a cubemap still samples from the texture. On xemu it just returns black for every sample.

HW results for this case: https://abaire.github.io/nxdk_pgraph_tests_golden_results/results/Texture_2D_as_cubemap/index.html

**Comment by antoniodesousa** [comment]
@abaire here are the renderdoc and PGRAPH event traces from both master and PR 2472.

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/b5eae134-e096-4d41-bc58-23fa799012e5" />

[Dinosaur Hunting - PR 2472.zip](https://github.com/user-attachments/files/22667464/Dinosaur.Hunting.-.PR.2472.zip)

### Fog issue
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/98dbaf2d-a48e-4391-a12b-88306a2319df" />
<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/a2a2b4b9-3a47-4556-ba4c-d3142d07c8e2" />

[Dinosaur Hunting - Master.zip](https://drive.google.com/file/d/18I9Vk8mJ-IAXoX-LO1-NaoRw0eKt5u4P/view?usp=drive_link)

**Comment by abaire** [comment]
Thanks!

> [@abaire](https://github.com/abaire) here are the renderdoc and PGRAPH event traces from both master and PR 2472.

Unfortunately this one looks like it's either an F12 capture or something went awry with the F10 cap. I see a portion of the guest draws but not an entire frame.

I think there's enough to say that the water env mapping looks fixed with the PR; the dark blotches on top look like they're some kind of cloud effect overlay. If you don't mind doing another capture of the PR #2472 build in roughly the same spot it'd be very interesting to see what causes them so we can decide how to split up this bug into distinct issues. You can double check that it's catching a full guest frame by filtering for `DRAW`, there should be well over 100 SET_BEGIN_END events in a guest-bounded cap in that area of the game.

**Comment by antoniodesousa** [comment]
> Unfortunately this one looks like it's either an F12 capture or something went awry with the F10 cap. I see a portion of the guest draws but not an entire frame.

Ah sorry, I did use F12... I must be asleep. You can still use the PGRAPH event traces from [Dinosaur Hunting - Master.zip](https://drive.google.com/file/d/18I9Vk8mJ-IAXoX-LO1-NaoRw0eKt5u4P/view?usp=drive_link).

[Dinosaur Hunting - PR 2472 F10.zip](https://drive.google.com/file/d/1sX_4d-pjPLhKaB3LhKNUXGwc8NAs3zdu/view?usp=drive_link)
[Dinosaur Hunting - Fog Master F10.zip](https://drive.google.com/file/d/18fjluQ14-kzUqRi0WZizyezQLvwqXjsx/view?usp=drive_link)

**Comment by abaire** [comment]
Thanks!

The PR2472 confirms that the black splotches are due to smoke textures being composited onto the env mapped water, so I'm very confident now that that is an entirely different issue. They are also not using fog at all, so it's likely separate from the fog master issue as well (I'll investigate that next).

Combiner for one of the smoke draws:
```
// Stage 0
mux_sum.rgb = clamp(vec3(((max(v0.rgb, 0.0) * max(t0.rgb, 0.0)) + (max(vec4(0.0).rgb, 0.0) * max(vec4(0.0).rgb, 0.0)))), -1.0, 1.0);
mux_sum.a = clamp((((max(v0.a, 0.0) * max(t0.a, 0.0)) + (max(vec4(0.0).b, 0.0) * max(vec4(0.0).b, 0.0)))), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
r0.a = mux_sum.a;
// Final Combiner
fragColor.rgb = max(r0.rgb, 0.0) + mix(vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(vec4(0.0).rgb, 0.0)));
fragColor.a = max(r0.a, 0.0);
```

The black spots only show up after multiple smoke passes are overlaid on each other. Initially I suspected a signed texture channel problem but I don't see signed textures in the PGRAPH trace from @Triticum0 or the master trace from @antoniodesousa .

In any case, I'm going to split this bug into three and have this thread focus on the env mapping issue since that's figured out now.

**Comment by abaire** [comment]
I've split this bug up:

* #1622 (this issue) will just cover the (solved) problem of 2d textures used for environment mapping expecting cubemaps/volumetric textures
* #2473 covers the black splotches due to the smoke draws
* #2474 covers the fog issue

Thanks for your help refining these issues!
