### ISSUE TITLE
Constantine - Intro and cutscenes play audio but not video.

### ISSUE THREAD

**Issue by sinfulsm** [xemu-project/xemu#2421]
### Title

https://xemu.app/titles/5343000f/#Constantine

### Bug Description

Intro and cutscenes play audio, but won't show video; menus and gameplay show and run just fine.

Steps to reproduce:
Load the game
Watch loading screen
*intro sequence plays audio but not video*
Load into main menu
Start game
*loading screen shows as intended*
*level cutscene plays audio but not video*
*gameplay works as intended*

### Expected Behavior

An intro sequence showing many company logos and cutscenes at the start of levels are expected to play video and sound.

### xemu Version

0.8.98

### System Information

OS: Windows 11
Processor: Ryzen 5 5600X 3.7ghz
Graphics card: NVIDIA RTX2060 6gb
Graphics Drivers: GeForce Game Ready Version 581.29

**Comment by Triticum0** [comment]
Make sure you dump your game correctly.

**Comment by antoniodesousa** [comment]
So, I was testing the game and I can confirm that all the FMV are black. I found that the last working Xemu build is v0.6.2.52. That means a commit between Jan 21, 2022 and Feb 11, 2022 is the culprit. Here's a list of all the commits between v6.2 and v6.3:
https://github.com/xemu-project/xemu/compare/v0.6.2...v0.6.3

But looking at the commits, the most likely culprit is this one https://github.com/xemu-project/xemu/commit/6b821d2062f28d8b04c7e02447ed066b50936eea

@abaire maybe you can look into it when you have time? Since it's your commit. Thanks.

**Comment by abaire** [comment]
I don't own that game, but if the FMV uses PVIDEO it definitely seems plausible. If somebody can get a RenderDoc capture I can look at it, though I don't recall how well PVIDEO is captured in RD. Somebody could also revert just that commit to see if the problem goes away.

**Comment by antoniodesousa** [comment]
> I don't own that game, but if the FMV uses PVIDEO it definitely seems plausible. If somebody can get a RenderDoc capture I can look at it, though I don't recall how well PVIDEO is captured in RD. Somebody could also revert just that commit to see if the problem goes away.

I can confirm that deleting this condition `!pvideo_color_key_enable || out_Color.rgba == pvideo_color_key` makes all the FMV visible. I tried to take a renderdoc capture but it crashes the emulator every time. Here's the PGRAPH trace event though. I'm not sure if it's useful.

[pgraph_trace_event.log](https://github.com/user-attachments/files/22319757/pgraph_trace_event.log)

**Comment by abaire** [comment]
Sorry, I forgot that all PVIDEO config is done directly through the PVIDEO subsystem. We'd need to look at the register write trace output https://github.com/xemu-project/xemu/blob/c67843384031e0edaab3db91ec496464b931789b/hw/xbox/nv2a/pvideo.c#L56 
I think you can enable the nv2a_reg_write trace, but it'll probably be chatty and may be easier to just do a temporary printf in that handler.

My hope is that the configuration will be obviously atypical and will be easy to reproduce in the [pvideo tests](https://github.com/abaire/nxdk_pgraph_tests/blob/main/src/tests/pvideo_tests.cpp) so it can be fixed without access to the game.

**Comment by antoniodesousa** [comment]
> I think you can enable the nv2a_reg_write trace, but it'll probably be chatty and may be easier to just do a temporary printf in that handler.

There you go 

[trace-event nv2a_reg_write.log](https://github.com/user-attachments/files/22321147/trace-event.nv2a_reg_write.log)

**Comment by abaire** [comment]
Thanks!

I've updated [nv2a-pretty](https://pypi.org/project/nv2a-pretty/) to expand PVIDEO register writes.

I've added a snippet of the log below. We can see that the color key is set to 0-alpha full black and that color keying is enabled. When I originally wrote the color key handling I had questions about the high byte in the color key, so it's possible that it has some interesting unimplemented effect.

It also looks like I never got around to writing PVIDEO tests that use color keying (just filed https://github.com/abaire/nxdk_pgraph_tests/issues/242 which should be a straightforward extension, I think all the necessary infra already exists).

---
Log start:

```
nv2a_reg_write PVIDEO [0x100] = 0x00000011: Interrupt reset: Buffer0: True, Buffer1: True
nv2a_reg_write PVIDEO [0x920] = 0x00000000: offset[0]: Offset: 0x00000000
nv2a_reg_write PVIDEO [0x928] = 0xffffffff: size_in[0]: 4095 x 4095
nv2a_reg_write PVIDEO [0x930] = 0x00000000: point_in[0]: 0, 0
nv2a_reg_write PVIDEO [0x900] = 0x00000000: base[0]: 0 (0x00000000)
nv2a_reg_write PVIDEO [0x910] = 0x00001000: luminance[0]: Contrast: 0x200, Brightness: 0x0
nv2a_reg_write PVIDEO [0x918] = 0x00001000: chrominance[0]: COS: 0x400, SIN: 0x0
nv2a_reg_write PVIDEO [0x704] = 0x00000000: Stop: Overlay active: False, Stop immediately: True
nv2a_reg_write PVIDEO [0xb00] = 0x00000000: color key: 0x00000000
nv2a_reg_write PVIDEO [0x920] = 0x01414000: offset[0]: Offset: 0x00050500
nv2a_reg_write PVIDEO [0x930] = 0x00000000: point_in[0]: 0, 0
nv2a_reg_write PVIDEO [0x928] = 0x01e00280: size_in[0]: 640 x 480
nv2a_reg_write PVIDEO [0x938] = 0x00100000: ds/dx[0]: UNITY
nv2a_reg_write PVIDEO [0x940] = 0x00100000: dt/dy[0]: UNITY
nv2a_reg_write PVIDEO [0x948] = 0x00000000: point_out[0]: 0, 0
nv2a_reg_write PVIDEO [0x950] = 0x01e00280: size_out[0]: 640 x 480
nv2a_reg_write PVIDEO [0x958] = 0x00110500: format[0]: Pitch: 1280, LE_CR8YB8CB8YA8, Color keyed, Matrix: ITURBT601
nv2a_reg_write PVIDEO [0x908] = 0x07ffffff: limit[0]: 2097151 (0x001fffff)

nv2a_reg_write PVIDEO [0x140] = 0x00000001: Interrupt enabled: Buffer0: True, Buffer1: False
nv2a_reg_write PVIDEO [0x700] = 0x00000001: Use: Buffer0: True, Buffer1: False
nv2a_reg_write PVIDEO [0x704] = 0x00000000: Stop: Overlay active: False, Stop immediately: True
nv2a_reg_write PVIDEO [0xb00] = 0x00000000: color key: 0x00000000
nv2a_reg_write PVIDEO [0x920] = 0x014aa000: offset[0]: Offset: 0x00052a80
nv2a_reg_write PVIDEO [0x930] = 0x00000000: point_in[0]: 0, 0
nv2a_reg_write PVIDEO [0x928] = 0x01e00280: size_in[0]: 640 x 480
nv2a_reg_write PVIDEO [0x938] = 0x00100000: ds/dx[0]: UNITY
nv2a_reg_write PVIDEO [0x940] = 0x00100000: dt/dy[0]: UNITY
nv2a_reg_write PVIDEO [0x948] = 0x00000000: point_out[0]: 0, 0
nv2a_reg_write PVIDEO [0x950] = 0x01e00280: size_out[0]: 640 x 480
nv2a_reg_write PVIDEO [0x958] = 0x00110500: format[0]: Pitch: 1280, LE_CR8YB8CB8YA8, Color keyed, Matrix: ITURBT601
nv2a_reg_write PVIDEO [0x908] = 0x07ffffff: limit[0]: 2097151 (0x001fffff)

nv2a_reg_write PVIDEO [0x140] = 0x00000001: Interrupt enabled: Buffer0: True, Buffer1: False
nv2a_reg_write PVIDEO [0x700] = 0x00000001: Use: Buffer0: True, Buffer1: False
nv2a_reg_write PVIDEO [0x704] = 0x00000000: Stop: Overlay active: False, Stop immediately: True
nv2a_reg_write PVIDEO [0xb00] = 0x00000000: color key: 0x00000000
nv2a_reg_write PVIDEO [0x920] = 0x01414000: offset[0]: Offset: 0x00050500
nv2a_reg_write PVIDEO [0x930] = 0x00000000: point_in[0]: 0, 0
nv2a_reg_write PVIDEO [0x928] = 0x01e00280: size_in[0]: 640 x 480
nv2a_reg_write PVIDEO [0x938] = 0x00100000: ds/dx[0]: UNITY
nv2a_reg_write PVIDEO [0x940] = 0x00100000: dt/dy[0]: UNITY
nv2a_reg_write PVIDEO [0x948] = 0x00000000: point_out[0]: 0, 0
nv2a_reg_write PVIDEO [0x950] = 0x01e00280: size_out[0]: 640 x 480
nv2a_reg_write PVIDEO [0x958] = 0x00110500: format[0]: Pitch: 1280, LE_CR8YB8CB8YA8, Color keyed, Matrix: ITURBT601
nv2a_reg_write PVIDEO [0x908] = 0x07ffffff: limit[0]: 2097151 (0x001fffff)
```

**Comment by antoniodesousa** [comment]
> We can see that the color key is set to 0-alpha full black and that color keying is enabled.

That would explain why the FMV are full black after implementing color keying on this game. Some cases or logic must be missing for sure.

**Comment by abaire** [comment]
> > We can see that the color key is set to 0-alpha full black and that color keying is enabled.
> 
> That would explain why the FMV are full black after implementing color keying on this game. Some cases or logic must be missing for sure.

It might, especially if the texture alpha is set to fully opaque black instead of fully transparent black. The easiest way to tell would be RenderDoc or nsight, if you can figure out why it's crashing. [v0.8.97](https://github.com/xemu-project/xemu/releases/tag/v0.8.97) added my fix for a case that caused RD to crash for certain titles, so if you're testing with an older build it'd be good to update or cherry-pick https://github.com/xemu-project/xemu/commit/1fedff47955f6f682ab2def8315ac0d16eade694.

Edit: In case you were using it - my `work` branch did not have this fix merged, it's now rebased and building a new artifact with the fix.

**Comment by antoniodesousa** [comment]
I have no idea what's going on with the crashes. It happens with any game from what I see. Even the games that I had capture renderdoc before. Only thing I did was update the GPU driver to Adrenalin 25.9.1 since last month.

<img width="400" height="300" alt="Image" src="https://github.com/user-attachments/assets/c1ffa64e-2ad7-42b0-8d13-3c31fcd4347c" />

Anyways, I just clicked ignore and it seemed to capture the renderdoc. I captured 3 just in case. Let me know if they are good.

[Constantine - Renderdoc.zip](https://github.com/user-attachments/files/22322715/Constantine.-.Renderdoc.zip)

**Comment by abaire** [comment]
> I have no idea what's going on with the crashes. It happens with any game from what I see. Even the games that I had capture renderdoc before. Only thing I did was update the GPU driver to Adrenalin 25.9.1 since last month.

It'd be interesting to see what glGetError actually returns there so we can get an idea as to what is failing.

In this case it looks like the captures contain good data anyway. The first interesting thing that I see is that the texture format is `0x1E` which is `NV097_SET_TEXTURE_FORMAT_COLOR_LU_IMAGE_X8R8G8B8` - I am not sure if we've definitively found that `X` is treated as `0` in all cases (I know there are X->Z and X->O conversions forcing alpha to `0` or `1` respectively). This could be a trivial mismatch where the unused alpha ends up failing the equals check in the shader.

As a quick hack to confirm whether this explains the issue, you could change `out_Color.rgba == pvideo_color_key` to `out_Color.rgb == pvideo_color_key.rgb` at https://github.com/xemu-project/xemu/blob/c67843384031e0edaab3db91ec496464b931789b/hw/xbox/nv2a/pgraph/gl/display.c#L78 so we're entirely ignoring alpha.

If that works, we can extend the PVIDEO tests to try various input texture formats to see how HW handles the alpha channel and possibly also bit depth conversions.

**Comment by antoniodesousa** [comment]
> As a quick hack to confirm whether this explains the issue, you could change `out_Color.rgba == pvideo_color_key` to `out_Color.rgb == pvideo_color_key.rgb`

Sadly, it did not fix it. All FMV are still black.
Is there a way to know what `glGetError()` is returning without using `printf`?

**Comment by antoniodesousa** [comment]
Forget what I said in my previous comment! It does fix all FMV being black.
I just forgot to switch to OpenGL... nice find!

**Comment by abaire** [comment]
> Sadly, it did not fix it. All FMV are still black. Is there a way to know what `glGetError()` is returning without using `printf`?

Interesting, I'll take a deeper look in the coming days.

There's no way to get the value of the geterror into an assert message (without something like a switch that varies the assert). The assert string is static.

**Comment by abaire** [comment]
Oh, cool. Then it's probably just some additional handling for x-alpha + color keying that needs to be implemented. Likely straightforward, worst case we just need to pass along the fact that the input texture's alpha is being discarded and limit the check to just the rgb channels.

**Comment by abaire** [comment]
FYI, I can reproduce the assert if I try to do an F12 renderdoc capture (which I think is actually the right thing to do for PVIDEO, since we want the final compositing draw). glGetError returns `GL_INVALID_OPERATION`, it'll need some backing up to figure out what exactly triggered the error.

**Comment by antoniodesousa** [comment]
Yep, F12 also triggers the assertion for me. This error only started happening recently because I captured a renderdoc for BloodRain 2 on September 4 and it didn't trigger any assertion. Might be the new Adrenalin driver 25.9.1like I first thought. 

Do you have any idea of what games might use the PVIDEO alpha channel? Well, Constantine seems to use it but I'm pretty sure it's not supposed to be full opaque lol

**Comment by abaire** [comment]
According to #547 that prompted the implementation in the first place, Seablade. I am not sure if it fixed any other games, I think the only way to tell would be to examine the reg write trace logs (or disable the handling and look for regressions). Probably easier to just write a test with the nxdk that exercises it though.

**Comment by Triticum0** [comment]
Tested seablade and NBA jam recently and there no Issues with regression from them in my testing. I would look at #1197 just in case
any of those issues are related. had this issue in past but thought my dump was the issue so never documented it. I would say most likely #1226 and Cold Fear same issue as regressed around the same time and exhibits the same behavior. #1185, #1047 also could be but dont know.

**Comment by Triticum0** [comment]
Yeah cold fear also seems to be a regression https://youtu.be/jgBhM9vAMVY?t=29

**Comment by abaire** [comment]
With a very basic test it looks like the color key should just entirely ignore alpha; it just operates on RGB matching. This aligns with what we found in this bug and what I found initially w/ Seablade where the top byte was set to 8 and was masked off.

I want to expand the test a bit further to check some other behavior but if this holds true it's just a trivial fix as above: https://github.com/xemu-project/xemu/issues/2421#issuecomment-3289757711.

**Comment by abaire** [comment]
Verified that alpha is ignored in various special surface formats as well and added PR #2428 to fix this.

I am not around a Vulkan-capable machine at the moment, @antoniodesousa or @Triticum0 would you be able to verify that the Vulkan change also works?

@Triticum0 if you could check Cold Fear with the PR build it'd be very much appreciated! I don't own that game.

**Comment by Triticum0** [comment]
Done and done, Yes both work with pr. Vulkan and cold fear

**Comment by Triticum0** [comment]
Tested breakdown, kill switch and Call of Cthulhu: Dark Corners and are unrelated to this issue

**Comment by abaire** [comment]
Excellent, thanks for your help as always!

**Comment by antoniodesousa** [comment]
I can confirm that PR https://github.com/xemu-project/xemu/pull/2428 fixes the FMV on both OpenGL and Vulkan. Hopefully the PR gets merged soon since is such a trivial change.
