### ISSUE TITLE
Wreckless: The Yakuza Missions Inaccurate reflections

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#2445]
### Bug Description

This game reflections seem to not match hardware. there way to bright in comparison to xbox ones.

Wreckless: The Yakuza Missions

<img width="640" height="480" alt="Image" src="https://github.com/user-attachments/assets/134225c9-9c69-43fe-a391-c3a8168b8f84" />

Hardware
<img width="1444" height="975" alt="Image" src="https://github.com/user-attachments/assets/1c2e949a-daa3-4fe9-8311-6d7aad44504f" />

### Expected Behavior

https://www.youtube.com/watch?v=z8PjB0AH32k

### xemu Version

0.8.101

### System Information

Field | Value
-- | --
OS | Windows 10
CPU | AMD Ryzen 5 5700x Eight-Core Processoe
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 581.29
Render | Opengl

**Comment by abaire** [comment]
Those ultrabright windows look like they could be using emissive lighting which still needs #2083 to match HW. Might be worth checking to see if that PR fixes it.

If not, if you can get a PGRAPH and renderdoc I can take a look.

**Comment by Triticum0** [comment]
Tested no change

Here a PGraph I did from earlier + Renderdoc

https://drive.google.com/file/d/1L8Wv8BJmeC0xoI8rRNHW5lEEMvw5_8pL/view?usp=sharing

[Wreckless Opengl.zip](https://github.com/user-attachments/files/22434401/Wreckless.Opengl.zip)

Note: This used to be an issue on second game but was fixed

**Comment by abaire** [comment]
Looks like the draw around EID 228616 is where things go awry.

Some of the previous draws build up something that looks like a light/bloom map where glowing elements (the windows, the car taillights) are rendered on a generally black texture. This draw composites this light map onto the framebuffer using the following combiner:

```
// Stage 0
mux_sum.rgb = clamp(vec3(((max(c0_0.aaa, 0.0) * t1.rgb) + (t2.rgb * (1.0 - clamp(c0_0.aaa, 0.0, 1.0))))), -1.0, 1.0);
mux_sum.a = clamp((((max(c0_0.a, 0.0) * t1.a) + (t2.a * (1.0 - clamp(c0_0.a, 0.0, 1.0))))), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
r0.a = mux_sum.a;
// Stage 1
mux_sum.rgb = clamp(vec3(((max(c0_1.aaa, 0.0) * t0.rgb) + (r0.rgb * (1.0 - clamp(c0_1.aaa, 0.0, 1.0))))), -1.0, 1.0);
mux_sum.a = clamp((((max(c0_1.a, 0.0) * t0.a) + (r0.a * (1.0 - clamp(c0_1.a, 0.0, 1.0))))), -1.0, 1.0);
t0.rgb = mux_sum.rgb;
t0.a = mux_sum.a;
// Stage 2
mux_sum.rgb = clamp(vec3(((t3.rgb * c0_2.rgb) + ((1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0)) * t0.rgb))), -1.0, 1.0);
mux_sum.a = clamp((((t3.a * c0_2.a) + ((1.0 - clamp(vec4(0.0).a, 0.0, 1.0)) * t0.a))), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
r0.a = mux_sum.a;
// Final Combiner
fragColor.rgb = max(vec4(0.0).rgb, 0.0) + mix(vec3(max(r0.rgb, 0.0)), vec3(max(c0_8.rgb, 0.0)), vec3(max(c0_8.aaa, 0.0)));
fragColor.a = max(r0.a, 0.0);
```

`c0_2` is `consts[4] 0.749019622803, 0.749019622803, 0.749019622803, 0.00 `

My guess is that either `c0_2` is incorrect (reducing these multipliers will reduce the intensity of the composited effect) or there is actually a problem building up the light map itself that is causing it to be overbright.

The light map has a final composition step around EID 227900 where all four texture units are set to a dim version of the map and it is redrawn with the following combiner:

```
// Stage 0
mux_sum.rgb = clamp(vec3(((t0.rgb * c0_0.rgb) + (t1.rgb * c1_0.rgb))), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
// Stage 1
mux_sum.rgb = clamp(vec3(((t2.rgb * c0_1.rgb) + (t3.rgb * c1_1.rgb))), -1.0, 1.0);
v1.rgb = mux_sum.rgb;
// Stage 2
mux_sum.rgb = clamp(vec3((((r0.rgb * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0))) + (c0_2.aaa * (2.0 * max(vec4(0.0).rgb, 0.0) - 1.0))) * 2.0)), -1.0, 1.0);
r0.rgb = mux_sum.rgb;
// Stage 3
mux_sum.rgb = clamp(vec3((((v1.rgb * (1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0))) + (c0_3.aaa * (2.0 * max(vec4(0.0).rgb, 0.0) - 1.0))) * 2.0)), -1.0, 1.0);
v1.rgb = mux_sum.rgb;
// Final Combiner
fragColor.rgb = max(vec4(0.0).rgb, 0.0) + mix(vec3(max(vec4(0.0).rgb, 0.0)), vec3(max(clamp(vec4(v1.rgb + r0.rgb, 0.0), 0.0, 1.0).rgb, 0.0)), vec3((1.0 - clamp(vec4(0.0).rgb, 0.0, 1.0))));
fragColor.a = max(vec4(0.0).b, 0.0);
```

The constants in this case are:
```
c0_0 = consts[0] 0.250980407, 0.250980407, 0.250980407, 0.00    float4
c1_0 = consts[1] 0.250980407, 0.250980407, 0.250980407, 0.00    float4
c0_1 = consts[2] 0.250980407, 0.250980407, 0.250980407, 0.00    float4
c1_1 = consts[3] 0.250980407, 0.250980407, 0.250980407, 0.00    float4
c0_2 = consts[4] 0.00, 0.00, 0.00, 0.00                       float4
c1_2 = consts[5] 0.00, 0.00, 0.00, 0.00                       float4
c0_3 = consts[6] 0.00, 0.00, 0.00, 0.00                       float4
```

Note that the constants are all slightly more than 0.25, meaning the resultant combination will be slightly more than 4x the original image intensity. Naively setting these to 0.25 does not seem to resolve the problem (surprisingly it's slightly worse).


@Triticum0 just to double check: are you absolutely certain these two captures are from the same level with the same weather/time-of-day/etc... effects from the game? To my eye it looks like the HW capture has no light map applied to the windows at all and the road texture also looks dramatically different (i.e., like it's not being lit from the windows) which makes me suspicious that some of this may be intentional.

I can see that there appears to be more of a lens flare effect on the taillights of the xemu cap than the HW so there is still likely some difference above the window lighting, but I'm not seeing an obvious problem that could explain the window lights being that much brighter without the taillights also being far brighter than HW as well.

**Comment by Triticum0** [comment]
Here another capture and screenshot on identical frame and reflection on top window look brighter than capture on youtube video.

https://drive.google.com/file/d/15zMjelqVHu0imXneugm0fIeJmbXczMAi/view?usp=sharing

<img width="1919" height="1079" alt="Image" src="https://github.com/user-attachments/assets/28a79c08-968a-419c-9891-51dfd0c0a846" />

https://youtu.be/z8PjB0AH32k?t=48

https://youtu.be/r0blfl_iuzo?t=31

[Wreckless second 2nd pgraph.zip](https://github.com/user-attachments/files/22549656/Wreckless.second.2nd.pgraph.zip)

FYI This game was never work on 360 emulator so youtube videos could only be played on hardware . Second video stated it played on original Xbox with identical look first video.
If you can't see anything I would just move on to something else. #1057 looks interesting as fire effect green on first boot once it shader cached the issue fixes itself also affect at least 3 game I tested. lotus challenge and curious geogre which you might have

**Comment by abaire** [comment]
Thanks! This one is similar, the interesting EIDs are 54270 (draw 471) and 55285 (draw 477).

Looks like the same combiner when building the light map:
```
// Color combiner:
0:
  C0 = (BLUE:40 0.250980, GREEN:40 0.250980, RED:40 0.250980, ALPHA:00 0.000000)
  C1 = (BLUE:40 0.250980, GREEN:40 0.250980, RED:40 0.250980, ALPHA:00 0.000000)
  R0Temp.rgb = SIGNED_IDENTITY(Tex0.rgb) * SIGNED_IDENTITY(C0.rgb) + SIGNED_IDENTITY(Tex1.rgb) * SIGNED_IDENTITY(C1.rgb)
1:
  C0 = (BLUE:40 0.250980, GREEN:40 0.250980, RED:40 0.250980, ALPHA:00 0.000000)
  C1 = (BLUE:40 0.250980, GREEN:40 0.250980, RED:40 0.250980, ALPHA:00 0.000000)
  V1_Specular.rgb = SIGNED_IDENTITY(Tex2.rgb) * SIGNED_IDENTITY(C0.rgb) + SIGNED_IDENTITY(Tex3.rgb) * SIGNED_IDENTITY(C1.rgb)
2:
  C0 = (BLUE:00 0.000000, GREEN:00 0.000000, RED:00 0.000000, ALPHA:00 0.000000)
  R0Temp.rgb = (SIGNED_IDENTITY(R0Temp.rgb) * (1.rgb) + SIGNED_IDENTITY(C0.a) * EXPAND_NORMAL(Zero.rgb)) * 2.0
3:
  C0 = (BLUE:00 0.000000, GREEN:00 0.000000, RED:00 0.000000, ALPHA:00 0.000000)
  V1_Specular.rgb = (SIGNED_IDENTITY(V1_Specular.rgb) * (1.rgb) + SIGNED_IDENTITY(C0.a) * EXPAND_NORMAL(Zero.rgb)) * 2.0
EFProd = (0.rgb) * (0.rgb)
Flags = specular_clamp
out.rgb = (0.rgb) + mix((0.rgb), (Specular_R0_Sum.rgb), (1.rgb)
out.a = (0.rgb)

== Draw 471 summary: ============
	Processed 286 PGRAPH commands
	Pipeline: Programmable
	Surface format: 0x8080228 {LE_A8R8G8B8, Z24S8, Type:Swizzle, AA:Center_1, Width:256, Height:256}
  	Surface pitch: 0x04000400 {Color:1024, Zeta:1024}
  	Surface color offset: 0x036A8000 => 57311232
  	Surface zeta offset: 0x00000000 => 0
  	Cull face: V_BACK
  	Depth write: OFF
  	Stencil write: OFF
  	Alpha blending:
  		Equation: <UNKNOWN>
  		Source factor: V_ONE
  		Destination factor: V_ONE
  		Color constant: <UNKNOWN>
  	Shader stages:
  		Stage 0: 2D_PROJECTIVE
  			Offset: 0x03907000 => 59797504
  			Format: 0x7710629 {DMA_A, BORDER_SOURCE_COLOR, SZ_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:128, BaseSizeV:128, BaseSizeP:1}
  			Address: 0x10404 {U:Border, V:Border, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
  			Border color: 0x00000000 => 0
  		Stage 1: 2D_PROJECTIVE
  			Offset: 0x03907000 => 59797504
  			Format: 0x7710629 {DMA_A, BORDER_SOURCE_COLOR, SZ_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:128, BaseSizeV:128, BaseSizeP:1}
  			Address: 0x10404 {U:Border, V:Border, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
  			Border color: 0x00000000 => 0
  		Stage 2: 2D_PROJECTIVE
  			Offset: 0x03907000 => 59797504
  			Format: 0x7710629 {DMA_A, BORDER_SOURCE_COLOR, SZ_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:128, BaseSizeV:128, BaseSizeP:1}
  			Address: 0x10404 {U:Border, V:Border, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
  			Border color: 0x00000000 => 0
  		Stage 3: 2D_PROJECTIVE
  			Offset: 0x03907000 => 59797504
  			Format: 0x7710629 {DMA_A, BORDER_SOURCE_COLOR, SZ_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:128, BaseSizeV:128, BaseSizeP:1}
  			Address: 0x10404 {U:Border, V:Border, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
  			Border color: 0x00000000 => 0

```

and the final composition:
```
// Color combiner:
0:
  C0 = (BLUE:00 0.000000, GREEN:00 0.000000, RED:00 0.000000, ALPHA:80 0.501961)
  R0Temp.rgb = (C0.a) * SIGNED_IDENTITY(Tex1.rgb) + SIGNED_IDENTITY(Tex2.rgb) * UNSIGNED_INVERT(C0.a)
  C0 = (BLUE:00 0.000000, GREEN:00 0.000000, RED:00 0.000000, ALPHA:80 0.501961)
  R0Temp.a = (C0.a) * SIGNED_IDENTITY(Tex1.a) + SIGNED_IDENTITY(Tex2.a) * UNSIGNED_INVERT(C0.a)
1:
  C0 = (BLUE:00 0.000000, GREEN:00 0.000000, RED:00 0.000000, ALPHA:55 0.333333)
  Tex0.rgb = (C0.a) * SIGNED_IDENTITY(Tex0.rgb) + SIGNED_IDENTITY(R0Temp.rgb) * UNSIGNED_INVERT(C0.a)
  C0 = (BLUE:00 0.000000, GREEN:00 0.000000, RED:00 0.000000, ALPHA:55 0.333333)
  Tex0.a = (C0.a) * SIGNED_IDENTITY(Tex0.a) + SIGNED_IDENTITY(R0Temp.a) * UNSIGNED_INVERT(C0.a)
2:
  C0 = (BLUE:BF 0.749020, GREEN:BF 0.749020, RED:BF 0.749020, ALPHA:00 0.000000)
  R0Temp.rgb = SIGNED_IDENTITY(Tex3.rgb) * SIGNED_IDENTITY(C0.rgb) + (1.rgb) * SIGNED_IDENTITY(Tex0.rgb)
  C0 = (BLUE:BF 0.749020, GREEN:BF 0.749020, RED:BF 0.749020, ALPHA:00 0.000000)
  R0Temp.a = SIGNED_IDENTITY(Tex3.a) * SIGNED_IDENTITY(C0.a) + (1.a) * SIGNED_IDENTITY(Tex0.a)
C0 = (BLUE:00 0.000000, GREEN:00 0.000000, RED:00 0.000000, ALPHA:00 0.000000)
EFProd = (0.rgb) * (0.rgb)
Flags = specular_clamp
out.rgb = (0.rgb) + mix((R0Temp.rgb), (C0.rgb), (C0.a)
out.a = (R0Temp.a)

== Draw 477 summary: ============
	Processed 599 PGRAPH commands
	Pipeline: Programmable
	Surface format: 0x113 {LE_R5G6B5, Z16, Type:Pitch, AA:Center_1, Width:1, Height:1}
  	Surface pitch: 0x05000500 {Color:1280, Zeta:1280}
  	Surface color offset: 0x03C46000 => 63201280
  	Surface zeta offset: 0x00000000 => 0
  	Cull face: V_BACK
  	Depth write: OFF
  	Stencil write: OFF
  	Shader stages:
  		Stage 0: 2D_PROJECTIVE
  			Offset: 0x037E8000 => 58621952
  			Format: 0x1122A {DMA_B, BORDER_SOURCE_COLOR, LU_IMAGE_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:1, BaseSizeV:1, BaseSizeP:1}
  			Address: 0x10303 {U:Clamp_Edge, V:Clamp_Edge, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
  			Control1: 0x8000000 {Pitch: 2048}
  			Image rect: 0x02000180 {H:384, W:512}
  		Stage 1: 2D_PROJECTIVE
  			Offset: 0x037E8000 => 58621952
  			Format: 0x1122A {DMA_B, BORDER_SOURCE_COLOR, LU_IMAGE_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:1, BaseSizeV:1, BaseSizeP:1}
  			Address: 0x10303 {U:Clamp_Edge, V:Clamp_Edge, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
  			Control1: 0x8000000 {Pitch: 2048}
  			Image rect: 0x02000180 {H:384, W:512}
  		Stage 2: 2D_PROJECTIVE
  			Offset: 0x037E8000 => 58621952
  			Format: 0x1122A {DMA_B, BORDER_SOURCE_COLOR, LU_IMAGE_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:1, BaseSizeV:1, BaseSizeP:1}
  			Address: 0x10303 {U:Clamp_Edge, V:Clamp_Edge, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
  			Control1: 0x8000000 {Pitch: 2048}
  			Image rect: 0x02000180 {H:384, W:512}
  		Stage 3: 2D_PROJECTIVE
  			Offset: 0x036A8000 => 57311232
  			Format: 0x8810629 {DMA_A, BORDER_SOURCE_COLOR, SZ_A8R8G8B8, MipmapLevels:1, 2D, BaseSizeU:256, BaseSizeV:256, BaseSizeP:1}
  			Address: 0x10303 {U:Clamp_Edge, V:Clamp_Edge, P:Wrap}
  			Filter: 0x2022000 {LODBias:0, Quincunx, Min:TentLOD0, Mag:TentLOD0}
  			Control0: 0x4003FFC0 {MaxAniso:1, MaxLOD:4095, MinLOD:0}
```

Still not sure what's going on here as these look reasonable to me at a glance. This could be a case of very small errors being compounded over time as the light map itself is composed over multiple draws using similar blends.


EDIT: It is interesting that the final composition writes to Tex0 in stage 1 of the combiner. I don't think I've tested HW behavior in this scenario and it's possible that it does something non-intuitive that would explain the dull output.
