### ISSUE TITLE
Terminator 3 The Redemption freezing before going ingame.

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#2503]
### Title

https://xemu.app/titles/4947003e/#Terminator-3-The-Redemption

### Bug Description

Both game freeze when trying to make it into gameplay. Rise of the Machines try to load in for few frame then freezes. Redemption audio plays for a while after the freeze then stops playing

Rise of the Machines Freeze

https://github.com/user-attachments/assets/b8b4c04d-45ac-40ac-8325-d6f8bb3f501e

Redemption Freeze

https://github.com/user-attachments/assets/519878b6-0f0d-48eb-9bfd-15adbd0b67a0

### Expected Behavior

Should not freeze

### xemu Version

v0.8.111

### System Information

Field | Value
-- | --
OS | Windows 11
CPU | AMD Ryzen 5 5700x Eight-Core Processoe
Graphics Device | NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
Graphics Driver | 4.0.0 NVIDIA 581.29
Render | Opengl

**Comment by saneFriend** [comment]
Tried out a save file just after the first cutscene that crashes and seems the game still randomly freezes during gameplay

**Comment by abaire** [comment]
Is the xemu UI still responsive or is xemu itself frozen?

If xemu is responsive, can you run `info registers` a few times in the monitor to see if `EIP` changes? It'd also be useful to paste the output of one of the runs.

**Comment by Triticum0** [comment]
Here you go. The EIP does change when running info registers on monitor

`CPU#0
EAX=00000000 EBX=00000000 ECX=d0036458 EDX=004a58c8
ESI=004a58e8 EDI=00000000 EBP=d0032850 ESP=d003281c
EIP=002bb6a7 EFL=00000282 [--S----] CPL=0 II=0 A20=1 SMM=0 HLT=0
ES =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
CS =0008 00000000 80060fff 00c89b00 DPL=0 CS32 [-RA]
SS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
DS =0010 00000000 ffffffff 00cf9300 DPL=0 DS   [-WA]
FS =0020 8004ac8c 00284fff 00c09300 DPL=0 DS   [-WA]
GS =0000 00000000 00000000 00000000
LDT=0000 00000000 0000ffff 00008200 DPL=0 LDT
TR =0018 8005e990 00000068 00008900 DPL=0 TSS32-avl
GDT=     8005eac8 00000038
IDT=     8004af38 00000200
CR0=80010031 CR2=00000000 CR3=0000f000 CR4=00000610
DR0=00000000 DR1=00000000 DR2=00000000 DR3=00000000 
DR6=ffff0ff0 DR7=00000400
EFER=0000000000000000
FCW=027f FSW=4000 [ST=0] FTW=00 MXCSR=00001fa0
FPR0=0000000000000000 0000 FPR1=0000000000000000 0000
FPR2=ffcd3d0000000000 3ffe FPR3=0000000000000000 0000
FPR4=ffcd3d0000000000 3ffe FPR5=b716830000000000 c005
FPR6=86da281318000000 4023 FPR7=d556000000000000 3ffd
XMM00=0000000000000000 0000000000000000 XMM01=0000000000000000 0000000000000000
XMM02=0000000000000000 0000000000000000 XMM03=0000000000000000 0000000000000000
XMM04=0000000000000000 0000000000000000 XMM05=0000000000000000 0000000000000000
XMM06=0000000000000000 0000000000000000 XMM07=0000000000000000 0000000000000000
`

**Comment by Triticum0** [comment]
Using a savefile allows you to make it ingame but still freezes after a while.

https://github.com/user-attachments/assets/a4e6f477-e8ad-4682-9903-f283e5c37212

**Comment by Triticum0** [comment]
Here a Renderdoc if it of any uses.
https://drive.google.com/file/d/1JR_WLGG2SEE_B4ofl_le26Qfmjyuo-8g/view?usp=sharing

**Comment by abaire** [comment]
Thanks, if EIP is changing then it's not hard frozen. It might be like #1962 where it's waiting on a nv2a semaphore update that never comes.

I ordered Rise of the Machines, will take a look in a week or two when it arrives.

**Comment by Triticum0** [comment]
Seems like terminator 3 Rise of the Machines an audio issue turn of audio completely should allow to make it ingame but I haven't been able to test that theory yet

**Comment by Triticum0** [comment]
terminator 3 Rise of the Machines fixed by #2945 makes it ingame

**Comment by audiowylde2345** [comment]
What about redemption?

**Comment by Triticum0** [comment]
Seems to be fixed by https://github.com/xemu-project/xemu/pull/2568 or pr afterwards, Need more testing to confirm whether freezing occurs later on like def jam but original freezing  spot seems to be fixed. @abaire Don't know if you have anyway of confirming that was what fixed it, as dev build overwrites previous builds.

**Comment by audiowylde2345** [comment]
I tried this once one of the developers said the regular Terminator 3 worked with a developer build and it was still freezing what build are you using? I'll test soon as I get home

**Comment by audiowylde2345** [comment]
So far works like a charm on my ally x. Using the newest dev build

**Comment by abaire** [comment]
> Seems to be fixed by [#2568](https://github.com/xemu-project/xemu/pull/2568) or pr afterwards, Need more testing to confirm whether freezing occurs later on like def jam but original freezing spot seems to be fixed. [@abaire](https://github.com/abaire) Don't know if you have anyway of confirming that was what fixed it, as dev build overwrites previous builds.

You can look up the pre-release builds via the actions page: https://github.com/xemu-project/xemu/actions/workflows/prerelease.yml but if it was definitely broken before #2568 was merged, there haven't really been any changes likely to affect it afterwards. Besides docs and UI-specific changes I think the only relevant change was a fix for an edge condition that #2568 introduced.

**Comment by Triticum0** [comment]
Confirming https://github.com/xemu-project/xemu/pull/2568 fixes the issue

**Comment by audiowylde2345** [comment]
Great job guys keep up the good work. I only have a handful of games left that don't work. Keep it up love this emulator
