### ISSUE TITLE
Project Gotham Racing running in severely low frame rates

### ISSUE THREAD

**Issue by LudicrousFool79** [xemu-project/xemu#480]
### Title

https://xemu.app/titles/4d530003/#Project-Gotham-Racing

NTSC MS-003 [4d530003] v1.0

### Bug Description

When loading in a vehicle at the car selection screen, the game's performance utterly tanks, as in it drops to single digits. In races, the game consistently runs below 30 FPS and appears to be at half-speed; pause menu, unbelievably, runs at an even lower frame it. Steps to reproduce:

1. Start the game
2. Navigate to any event in any mode and select it
3. Go into car selection screen 

Voila, single digit FPS is yours.

For the races, there are a further three steps:

1. Select car
2. Then select start race
3. The game loads into a race, and once again, you're met with low frame rates

https://user-images.githubusercontent.com/92067708/136308679-d0f92b08-ac3d-49cc-a717-f7539503d94f.mp4

https://user-images.githubusercontent.com/92067708/136308961-12d05add-22e1-45ee-b981-f104173b2de7.mp4

https://user-images.githubusercontent.com/92067708/136309005-d59cd10e-4f52-4a09-bfd9-8c53fc7e4a4e.mp4

### Expected Behavior

Expect the game to run what feels like half-speed during the races and menus in which there is slowdown. There are also noticeable visual bugs during gameplay such as car shadows not displaying at all and walls abruptly disappearing when they reach the edges of the side of the screen.

### xemu Version

0.6.1-12-ga8c73197da

### System Information

OS: Windows
CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60 GHz
GPU: Nvidia GeForce RTX 2080 Super
GPU Driver: Nvidia(R) GeForce(R) Experience(TM) Driver version 471.68

**Comment by LeRutY** [comment]
0.5.1-3-ge1f548aa2b doesn´t have the slowdowns but it may be not the last build before it has gotten worse

**Comment by charlestudor** [comment]
Hi, just to help narrow this down: It appears build 0.5.4-39 ( build-202107201737 / https://github.com/mborgerson/xemu/commit/edf373571879bf90baeeb617aa9a0a1cde25097b ) is the one which introduces the slowdowns. 

The previous build 0.5.4-29 (build-202107190558 ) does not seem to have them.

For anyone here looking to get the game running like I was, a previous build like 0.5.4-29 has better framerates but other problems like audio such that I wouldn't consider it "Playable" I'm afraid!

Hope this is useful

**Comment by LeRutY** [comment]
Testing 0.6.3 right now and the slowdowns no longer occure

**Comment by pinchies** [comment]
I'm seeing all of the issue symptoms still present in v 0.6.6 -- half speed gameplay, no shadows, walls disappearing as they approach the edges of field of view.

**Comment by LeRutY** [comment]
> I'm seeing all of the issue symptoms still present in v 0.6.6 -- half speed gameplay, no shadows, walls disappearing as they approach the edges of field of view.

Half speed gameplay is caused by slow hardware and the still unoptimized emulator, it´s one of the game which are demanding. Broken graphics are a different issue, this one is / was about the performance

This issue can be closed because the regre
![Fixed](https://user-images.githubusercontent.com/29675883/168289204-ed7a1407-a348-40cd-bd87-ad4a42f9e2b6.png)
ssion has been fixed, not sure since when

**Comment by LeRutY** [comment]
> I'm seeing all of the issue symptoms still present in v 0.6.6 -- half speed gameplay, no shadows, walls disappearing as they approach the edges of field of view.

Half speed gameplay is caused by slow hardware and the still unoptimized emulator, it´s one of the game which are demanding. Broken graphics are a different issue, this one is / was about the performance

This issue can be closed because the regression has been fixed, not sure since when

![Fixed](https://user-images.githubusercontent.com/29675883/168289385-c09d57d6-ac69-4d33-8d48-4319e9d023ee.png)

**Comment by LeRutY** [comment]
> I'm seeing all of the issue symptoms still present in v 0.6.6 -- half speed gameplay, no shadows, walls disappearing as they approach the edges of field of view.

**Comment by LeRutY** [comment]
> I'm seeing all of the issue symptoms still present in v 0.6.6 -- half speed gameplay, no shadows, walls disappearing as they approach the edges of field of view.

Half speed gameplay is caused by slow hardware and the still unoptimized emulator, it´s one of the game which are demanding. Broken graphics are a different issue, this one is / was about the performance

This issue can be closed because the regression has been fixed, not sure since when

![Fixed](https://user-images.githubusercontent.com/29675883/168289675-e578e951-235f-4890-80c9-7e393d19809e.png)

**Comment by davedoc1984** [comment]
Why is this closed down? The issue still very much remains. My Hardware I wouldn't say is slow. PGR 2 is affected in the same way.

i7 12700H
RTX 3070 Laptop GPU
16GB of DDR 4 RAM
1TB NVME Gen 4 SSD

**Comment by samuel-cezar** [comment]
Still happening I'm on XEMU 0.7.120;
Did anyone found a way to fix this?
My specs are:

Windows 10 Latest Update
i9 9900K
RTX 3060 12GB 
32GB DDR4 3000mhz
1TB Sata SSD

**Comment by SplatsMod** [comment]
The issue is still happening on version 0.7.121, apparently disabling the Multi-threaded Optimizations from Nvidia (if you have a Nvidia GPU) can positively impact a little bit on its performance, specially if you drive in 1st person view, but the framerate is still slow.

Specs:
Intel Core i7 7700K
Nvidia GeForce RTX 2060 6GB
16GB DDR4 RAM 2400Mhz speed

**Comment by PGRfanatic** [comment]
Any Update on when this issue will be fixed? I am running latest version and its terrible once the game is loaded.

Ive tried on a macbook pro m2 pro and windows pc i9 14900k Nvidia RTX 4080. both computers work perfectely in the menu but once the game is loaded it is unbearably slow

**Comment by snoozi** [comment]
Spec: AMD 5600X, AMD RX 6800, 32GB RAM, Gen 3 SSD
OS: Windows 11 23h2 with latest updates
Emulator Version: 0.7.131-114-g4b1c0b7fc7

I'm finding that I can run PGR1 at 59-60 FPS (2x int res, Vulkan and OGL) on a lot of maps if I switch to a camera mode that doesn't display my car, any car inside of my car, and any car ahead of me or a little bit behind me. Once ghosts/AI cars are far enough behind me, they don't seem to affect the performance as much anymore and the game becomes more playable again.

If I even have so much as a ghost car in something like time attack, the performance is close to halved -- ~30-40 FPS range. Resetting the ghost brings me back to 59-60 FPS. 

Hypothesized cause of slowdowns: Displaying/rendering any car including my own on the screen is repeatedly a huge performance drop. It also affects menus when it's occurring.

**Comment by Triticum0** [comment]
Should be fixed by #1886  at least on my system a lock 60. retest

**Comment by pinchies** [comment]
Ok, just retested it. It is improved, but, there are still severe slowdowns here and there in game during racing unfortunately. 

Now there are some times where everything is relatively smooth, and is actually real-time!! -- especially when most of the other cars are out of view. Audio still pretty terrible during race. Graphical appearance is excellent now too. Car selection menu screen is also much much better now, only little hiccup here and there... 

I don't think we can call this issue resolved yet, as the main issue of severe slowdowns during racing is still occurring. Seems to be worse with the Mini cooper for some reason.

I tried both rendering engines, found significantly better performance on OpenGL than Vulkan. GTX1080Ti, i9 7900X -- I found at least 3 cores pegged to 100% load at all times.

**Comment by BCoder395** [comment]
Testing the latest March 19th build and it seems that the audio problem is only in the full grid races so far. Races with just the player's car or with one opponent has the audio sounding perfectly fine. Also, the frame rate slows when there are too many things on-screen when it should maintain its frame rate.

**Comment by BCoder395** [comment]
Re-tested on one of the latest builds (EDIT: with multi-threaded optimisation enabled). There's minor slowdown (around 30-40 fps) in Tokyo, and MAJOR slowdown (single to two digit frames) in New York, on full grid races. There's only little slowdown in SF and London before the race starts, but runs at full speed. Running the game on a ASUS TUF Gaming A15 with a Ryzen 7000 Series (3GHz+), a nVidia GeForce 4050 RTX (6GB+) and 16GB of RAM.

**Comment by jammydrury** [comment]
Large frame drops on multiple levels, worse with CPU/AI cars. Inconsistent Input lag is a big issue when the game slows down for beating Style challanges.

CPU:12400F 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/7db0475d-3296-4ad7-ac42-e168dc14730a" />

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/25f70cf5-99b2-4868-a4f2-dfb73a8c4315" />

**Comment by SplatsMod** [comment]
Tested on Xemu 0.8.96 (latest version of the emulator), frame drops are incredibly and most notably present in areas like New York, things worsen when there's AI racers. Loading the pause menu causes a more larger frame drop as showcased in the second screenshot sometimes. San Francisco maps are the ones where frame drops are less notable, but still present.

<img width="1670" height="974" alt="Image" src="https://github.com/user-attachments/assets/2cc106f4-89ee-4b6f-bf62-72fa366bbe00" />

<img width="1564" height="964" alt="Image" src="https://github.com/user-attachments/assets/2f15db32-33a0-4fcd-8c14-f5ce2b9d2264" />

<img width="1567" height="976" alt="Image" src="https://github.com/user-attachments/assets/f8f340b6-f2b5-423e-8fa4-9fbe32140438" />

Running this on:
- CPU: Intel Core i7 7700K 4.2Ghz
- GPU: Nvidia GeForce RTX 2060 6GB
- 16GB DDR4 RAM

**Comment by Kingedeji** [comment]
Hello there. I'm using Nvidia driver settings, 'fast' v-sync, multithreaded optimization 'off' and Low latency 'On' - Vulkan @ 2X and I went from the reported half frame rate slow-mo to mostly full speed, all good and playable. Races with ai still chug a little but I'm rocking a 12400f and a 1070 Ti here so go figure. Not 100% on if vsync or not but I'm guessing it's the low latency mode but I should test more. Hope this helps someone or someone else can confirm. I'm using latest build and have had the same issue over multiple build over past year or so. Never tried low latency modes before.

**Comment by SplatsMod** [comment]
> Hello there. I'm using Nvidia driver settings, 'fast' v-sync, multithreaded optimization 'off' and Low latency 'On' - Vulkan @ 2X and I went from the reported half frame rate slow-mo to mostly full speed, all good and playable. Races with ai still chug a little but I'm rocking a 12400f and a 1070 Ti here so go figure. Not 100% on if vsync or not but I'm guessing it's the low latency mode but I should test more. Hope this helps someone or someone else can confirm. I'm using latest build and have had the same issue over multiple build over past year or so. Never tried low latency modes before.

I have a question regarding this, did you have to reset your PC in order for the changes on the GPU to apply?

**Comment by Kingedeji** [comment]
> > Hello there. I'm using Nvidia driver settings, 'fast' v-sync, multithreaded optimization 'off' and Low latency 'On' - Vulkan @ 2X and I went from the reported half frame rate slow-mo to mostly full speed, all good and playable. Races with ai still chug a little but I'm rocking a 12400f and a 1070 Ti here so go figure. Not 100% on if vsync or not but I'm guessing it's the low latency mode but I should test more. Hope this helps someone or someone else can confirm. I'm using latest build and have had the same issue over multiple build over past year or so. Never tried low latency modes before.
> 
> I have a question regarding this, did you have to reset your PC in order for the changes on the GPU to apply?

No, driver changes are instant. I only restarted Xemu and yeah, could do time trials and challenges easily whereas before was a literal slow-mo festival. I did not do any more 'experiments' my settings were generally fine for most other games but PGR was very poor performance. I will try to check more later. I'm banking on low-latency but is probably just the vsync

**Comment by jammydrury** [comment]
**CPU**: 12400F **RAM**: 32GB 3200Mhz

**Level 9**: Challenge Tour 
**Race 6**: Timed Run 
**Location**: New York - Times Square

I can't beat this race at the moment because of how slow sections of the track are, **very low fps**. I tried @Kingedeji fix recommendation and it didn't help.

**Comment by christian-4211** [comment]
Having similar issues as other people. 

RTX 2060 6 GB VRAM
16GB RAM
Core i7 9750H
4TB Crucial X9 

Game loads fine - menu seems to be running in full speed. 
As soon as I load into an arcade race, everything is sub-10 fps. 

It feels like I'm underwater, the fps is low and the audio is slowed as well. My laptop has issues running Xenia Canary (Xbox 360 exp. emulator), but even then I can run many games at 20-45 fps. So getting such a low fps rate here is pretty shocking.

**Comment by SplatsMod** [comment]
As of Xemu 0.8.119, Project Gotham Racing keeps having the same performance issues.

- RTX 2060 6GB
- 16GB RAM
- Intel Core i7 7700K

<img width="1153" height="803" alt="Image" src="https://github.com/user-attachments/assets/7eca4eea-9571-4211-ac27-8a375c920c17" />
<img width="1411" height="925" alt="Image" src="https://github.com/user-attachments/assets/7b592f51-0859-4d3f-b4dd-a6f5e78a7b0b" />
<img width="1376" height="916" alt="Image" src="https://github.com/user-attachments/assets/4e6ac114-28d8-49f1-a2cc-809542a8b8f1" />

Sometimes, although when playing alone, framerate is somewhat stable (depends on the area of the map)

<img width="1329" height="940" alt="Image" src="https://github.com/user-attachments/assets/e9099f17-3721-4cc3-9e4d-92647c588796" />

**Comment by czerwinski76** [comment]
@SplatsMod What about your CPU and GPU usage please ?

**Comment by LemurCat0247** [comment]
This is still an issue in Xemu 0.8.134

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/3a3487f1-ac34-45ee-8adb-2f721021d8ae" />

**Comment by SplatsMod** [comment]
As of 0.8.134, PGR 1 still suffers from low framerates

<img width="1920" height="978" alt="Image" src="https://github.com/user-attachments/assets/6718a3c7-4b88-4979-9741-3f32b504e1c6" />
<img width="1920" height="965" alt="Image" src="https://github.com/user-attachments/assets/8ffb16ff-e6e8-4755-93f7-7b349f3e7e16" />
<img width="1920" height="952" alt="Image" src="https://github.com/user-attachments/assets/58430d97-be03-40c0-b500-d207a8e2fade" />

**Comment by barrett256** [comment]
In PGR 1, I encounter the same issue on my laptop (with RTX 4050), mini-pc (AMD Vega 8), and with my most powerful machine:

Windows 11
Intel Core i5-13400F
32GB DDR4 RAM
RTX 4070 12GB

**Comment by Maxkatsur** [comment]
Persistent issue... maybe blending, shuffling, RT in RT stuff, feedback reads, multidraw framebuffer copy, depth testing and sampling, pre-clamping of ST coordinates when they may overflow, etc (or NV2A equivalents) can help, as conformed in PCSX2 2.0 and later updates... but milestones when?

Xemu version 0.8.136-5-g67cc79e663
My laptop:
-Windows 11
-Intel Core i7-12650H
-Nvidia GeForce RTX 4050 Mobile 6GB
-16GB DDR4-SODIMM RAM

<img width="1920" height="1032" alt="Image" src="https://github.com/user-attachments/assets/7d750928-cc3d-4af7-a9ba-a580cff17e2c" />
2x IR, Vulkan & OpenGL


<img width="1640" height="992" alt="Image" src="https://github.com/user-attachments/assets/e1e96108-907b-4e7f-bfeb-2f7bf6e823c1" />
1x IR, Vulkan

**Comment by dsvid** [comment]
> This is still an issue in Xemu 0.8.134
> [<img alt="Image" width="1920" height="1080" src="https://private-user-images.githubusercontent.com/270121657/567406199-3a3487f1-ac34-45ee-8adb-2f721021d8ae.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODYwMjg4MzUsIm5iZiI6MTc4NjAyODUzNSwicGF0aCI6Ii8yNzAxMjE2NTcvNTY3NDA2MTk5LTNhMzQ4N2YxLWFjMzQtNDVlZS04YWRiLTJmNzIxMDIxZDhhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgwNlQxNTAyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZTgwMWU3NDAxMzBmNjg2ZDczODMwYzQ2OWQ3ODk1NDgxZTE2MDg1NWQxZWMxNDdkZmQ1OTk4Nzk2OGY4MTliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.2kxbxP_2hwTjBOXrbTaAgAlZiyoUgi3OyoXsHZX66-o">](https://private-user-images.githubusercontent.com/270121657/567406199-3a3487f1-ac34-45ee-8adb-2f721021d8ae.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODYwMjg0NzksIm5iZiI6MTc4NjAyODE3OSwicGF0aCI6Ii8yNzAxMjE2NTcvNTY3NDA2MTk5LTNhMzQ4N2YxLWFjMzQtNDVlZS04YWRiLTJmNzIxMDIxZDhhZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgwNlQxNDU2MTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZTAwMDRlOGFmODg0YWU5NjAwYWE0MDhlZGM1MDQ5OTdiNmJhZThkMjY4YWU2NjlkMDMwNDMzZGI0NTc0ZmE3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.y4LCxPdU1TJq8J6quKA637_YCFGhw68Ybwy74fv6XEc)

could you share your system information? Also which GPU and driver are you using? It seems like this is the only comment from someone experiencing performance issues on Linux.

I have been doing some experimentation with a consistent scene which is to open the game, go to quick race and use the default car and track settings (Mini Cooper and San Francisco). This is a multi-car race which seems to be where the game struggles the most.

Using this as a consistent test scene, I observed that on Windows on the current latest xemu version (v0.8.136) I get between around 30 to 40fps (average on the lower end probably ~32fps).

I tried the same on Linux (specifically Ubuntu 24.04.4 LTS) and was surprised to see that it actually hits 60fps. It's not a locked 60 but it performs significantly better than on Windows. Screenshot below from Linux.

xemu v0.8.136 on Ubuntu 24.04.4 LTS 

<img width="1282" height="998" alt="Image" src="https://github.com/user-attachments/assets/2ebf6535-4dc3-4793-8125-1245f3f2ceaf" />

I tried a bit of a binary search by using some older versions and found that on any 0.7.x version I was getting around the 30 to 40fps that I was seeing on Windows.

I tried the latest 0.7.x version that I could find see below

xemu v0.7.142 on Ubuntu 24.04.4 LTS

<img width="1282" height="998" alt="Image" src="https://github.com/user-attachments/assets/afecd57d-0d22-4a65-ae76-62aa6794601a" />

and then the earliest 0.8.x version

xemu v.0.8.0 on Ubuntu 24.04.4 LTS under OpenGL

<img width="1282" height="998" alt="Image" src="https://github.com/user-attachments/assets/a8d8a161-c394-427c-974b-9a3997aae8d7" />

it actually runs worse on Vulkan (same version and OS just switched to Vulkan)

<img width="1282" height="998" alt="Image" src="https://github.com/user-attachments/assets/3eb85d2f-0abe-4165-84f5-6279d66bb082" />

It seems like something between between the last 0.7.x and earliest 0.8.x has improved performance for this game under Linux, but seemingly not under Windows (I haven't yet A/B tested a 0.7.x version under Windows compared to 0.8.x but going off memory the latest version feels like it runs similarly to the last time I tested PGR on xemu on Windows a couple of years ago. Will test properly and report back if my assumption is incorrect).

I would like to know if anyone else is able to reproduce this?

My system specifications are

motherboard: MSI B550A-Pro
CPU: Ryzen 5600X
GPU: Radeon 9070XT
RAM: 32GB
Linux: Mesa 25.2.8 (radeonsi), kernel 6.17, Ubuntu 24.04.4

Specific xemu versions I tested on Linux: 0.7.75, 0.7.125, 0.7.134, 0.7.142 (all ~30-40fps) and 0.8.0, 0.8.3, 0.8.6, 0.8.31, 0.8.130, 0.8.131, 0.8.136 (all ~60fps)

**Comment by LemurCat0247** [comment]
The game does run a bit better on linux with openGL rather than Vulkan, but for me it was quite a small difference in a multi-car race (10-11 to 12-13 fps), while on a single-car race it was a much more significant improvement, getting about 10 fps more with OpenGL (~13 fps to ~23 fps). Also, Vulkan uses significantly more memory, close to twice as much.
System: 
Operating System: Debian GNU/Linux 13
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz
Memory: 16 GiB of RAM (15.5 GiB usable)
Graphics Processor 1: Intel® HD Graphics 530
Graphics Processor 2: NVIDIA GeForce GTX 970M (I haven't gotten Xemu to use this yet)

**Comment by dsvid** [comment]
> The game does run a bit better on linux with openGL rather than Vulkan, but for me it was quite a small difference in a multi-car race (10-11 to 12-13 fps), while on a single-car race it was a much more significant improvement, getting about 10 fps more with OpenGL (~13 fps to ~23 fps). Also, Vulkan uses significantly more memory, close to twice as much. System: Operating System: Debian GNU/Linux 13 Graphics Platform: Wayland Processors: 8 × Intel® Core™ i7-6700HQ CPU @ 2.60GHz Memory: 16 GiB of RAM (15.5 GiB usable) Graphics Processor 1: Intel® HD Graphics 530 Graphics Processor 2: NVIDIA GeForce GTX 970M (I haven't gotten Xemu to use this yet)

thanks for the extra info, if you manage to get it running on the 970M could you report back?

Perhaps this command might work?

`__NV_PRIME_RENDER_OFFLOAD=1 __GLX_VENDOR_LIBRARY_NAME=nvidia ./xemu.AppImage`

**Comment by LemurCat0247** [comment]
Yes, while testing on the 1st kudos challenge 1v1 race, I got pretty consistent 20-30 fps with the intel graphics, with ~50% cpu usage. Using the 970m, the framerate was extremely similar, although it did seem to be slightly faster on average. Cpu usage was the same and gpu usage was 20-30%. However, there was a clear difference on the car select screen; With intel graphics it was around 30 fps while with the nvidia it was around 45 fps. Also, it might be a configuration issue on my part but the emulator crashes if I try to switch it to vulkan.

**Comment by czerwinski76** [comment]
défi Kudo > introduction > course de rues
60 FPS with OpenGL (Vulkan makes my game run slowly)
Native emulator's options

<img width="642" height="512" alt="Image" src="https://github.com/user-attachments/assets/7c5c5dde-dc42-4b19-a90e-8bd95ced393d" />
<img width="642" height="512" alt="Image" src="https://github.com/user-attachments/assets/d1de6078-286c-448a-bb99-4c54172d534d" />
<img width="642" height="512" alt="Image" src="https://github.com/user-attachments/assets/71c47d69-e1e5-4f76-85ce-cf07ab65f08e" />

xemu v0.8.136
Windows 10 x64 22H2 (19045.7548)
Ryzen 9 9950x3D
Nvidia RTX 5070 (Geforce Game Ready driver 610.88)
32 Go DDR5-5600

**Comment by SplatsMod** [comment]
> défi Kudo > introduction > course de rues 60 FPS with OpenGL (Vulkan makes my game run slowly) Native emulator's options
> <img alt="Image" width="642" height="512" src="https://private-user-images.githubusercontent.com/19463267/633616005-7c5c5dde-dc42-4b19-a90e-8bd95ced393d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODc3NzI3OTYsIm5iZiI6MTc4Nzc3MjQ5NiwicGF0aCI6Ii8xOTQ2MzI2Ny82MzM2MTYwMDUtN2M1YzVkZGUtZGM0Mi00YjE5LWE5MGUtOGJkOTVjZWQzOTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODI2VDE5MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyNWEwNmU2MGRiMmI1ZTRiZTVhYTU0ZDUzNDliMDc5MmQ3NWRkMzQwZDVhMWU3MzYxMTU1YmFkMTQzMmZmMjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.WlXaQ8h5C4PJ69rJNuXwo0mVIPwo7iOMV9fkCXwWf2M"> <img alt="Image" width="642" height="512" src="https://private-user-images.githubusercontent.com/19463267/633616006-d1de6078-286c-448a-bb99-4c54172d534d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODc3NzI3OTYsIm5iZiI6MTc4Nzc3MjQ5NiwicGF0aCI6Ii8xOTQ2MzI2Ny82MzM2MTYwMDYtZDFkZTYwNzgtMjg2Yy00NDhhLWJiOTktNGM1NDE3MmQ1MzRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODI2VDE5MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2NTRiMWIxZDFkMmEyZDVmOWRmNTJjZmM4M2E5OTk3NzIzZDE3M2VmMzUzNzQxNzFmZGM2ZjM0MjU5MzA3MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.fwq2mqKWcJp7GO8l3eMsR8JwqjO7KlBsFKAL0n1a4fI"> <img alt="Image" width="642" height="512" src="https://private-user-images.githubusercontent.com/19463267/633616007-71c47d69-e1e5-4f76-85ce-cf07ab65f08e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODc3NzI3OTYsIm5iZiI6MTc4Nzc3MjQ5NiwicGF0aCI6Ii8xOTQ2MzI2Ny82MzM2MTYwMDctNzFjNDdkNjktZTFlNS00Zjc2LTg1Y2UtY2YwN2FiNjVmMDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA4MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwODI2VDE5MjgxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhOTg2MDg0NjE0ODhiOTM1ZWMyZWQ1YzNlMTk0MTAyM2YwZDMzZDU2MmExMDU1OTAwZjg4ZWQ4NTdiZGMzNTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.DWEoM7fydE7vALZa7OI17Dp2V-U7e5UgHA8aV244vow">
> 
> xemu v0.8.136 Windows 10 x64 22H2 (19045.7548) Ryzen 9 9950x3D Nvidia RTX 5070 (Geforce Game Ready driver 610.88) 32 Go DDR5-5600

New York works pretty badly according to people. Can you try any NY track to see how much FPS are you getting??

**Comment by HMrgts417** [comment]
Hello, I'm not too sure to report as new issue or not thus reporting here.
Please let me know if new thread is needed, thank you.

Specification:
xemu v0.8.136
Windows 10 x64 22H2 19045.6466
Intel Core 13th Gen i7-13700HX
Nvidia GeForce RTX 4070 Laptop 8GB
Nvidia App version 11.0.9.239
RAM 32GB 4800MHz SO-DIMM

Issue:
This New York even cannot be repeated after finished once, switching between OpenGL and Vulkan has no effect

<img width="1706" height="960" alt="Image" src="https://github.com/user-attachments/assets/18d0a9b4-8089-497c-86f2-17d2ce84220c" />

**Comment by czerwinski76** [comment]
@HMrgts417 Here where are talking about frame rate.
It think that you have not posted in the right place. Please open your own topic please 😇.
