### ISSUE TITLE
Rendered text glyphs apparently offset in various titles When Upscaling

### ISSUE THREAD

**Issue by Triticum0** [xemu-project/xemu#576]
### Title

https://xemu.app/titles/56550005/#Buffy-the-Vampire-Slayer-Chaos-Bleeds
https://xemu.app/titles/4d570005/#Area-51
https://xemu.app/titles/4c410004/#Star-Wars-The-Clone-Wars
https://xemu.app/titles/4343000b/#Lakemasters-Bass-Fishing-Game
https://xemu.app/titles/4b4f0003/#Dynasty-Warriors-3
https://xemu.app/titles/4b4f0004/#Dynasty-Warriors-4
https://xemu.app/titles/4d570012/#FireBlade
https://xemu.app/titles/4d53000f/#RalliSport-Challenge

### Bug Description

Some games have letters slightly cutoff as the letter seems to be one pixel to 2 pixels offset causing some artefacts in the typeface in menus. Depending on the typeface present In-game also affects the in-game font.
Area 51 xemu:
![Screenshot from 2021-11-30 16-15-19](https://user-images.githubusercontent.com/71127352/144098855-dbc7b12a-d715-4102-b45c-faeb46deabde.png)

xbox:
![Screenshot from 2021-11-30 16-31-45](https://user-images.githubusercontent.com/71127352/144098822-8af3c2d4-db38-4658-aab0-584f26eda5cc.png)
Buffy the vampire slayer: chaos bleeds xemu(Look at the letter T, t, r  and g): 
![Screenshot from 2021-11-30 17-15-53](https://user-images.githubusercontent.com/71127352/144099040-32e9214b-b0e3-4939-9a94-3ca5de3aeebc.png)

![Screenshot from 2021-11-30 17-16-07](https://user-images.githubusercontent.com/71127352/144099068-2ac2fa92-8f8c-49fb-995d-86e64052a7e8.png)

![Screenshot from 2021-11-30 17-16-17](https://user-images.githubusercontent.com/71127352/144099595-45d8c5c3-0f95-4518-bab4-2548b77861d5.png)

![Screenshot from 2021-11-30 17-16-22](https://user-images.githubusercontent.com/71127352/144100755-2ea51dd6-8feb-4065-8ef7-e8450ebb1f2d.png)

xbox:
![Screenshot from 2021-11-30 17-45-24](https://user-images.githubusercontent.com/71127352/144100261-b15025ab-f752-48e6-bf67-bba98f8d5815.png)
![Screenshot from 2021-11-30 17-46-47](https://user-images.githubusercontent.com/71127352/144100565-e7d6354f-41db-4c8f-925a-91041d32e7f5.png)

![Screenshot from 2021-11-30 17-45-54](https://user-images.githubusercontent.com/71127352/144100269-d5bbc422-1483-4bd6-866f-5b086957dfa4.png)

![Screenshot from 2021-11-30 17-45-57](https://user-images.githubusercontent.com/71127352/144100276-f54d5069-3d36-44a9-b685-aa545485b5d3.png)

### Expected Behavior

should look the same as it does on console.

### xemu Version

Version: 0.6.2
Branch: master
Commit: 69ceec4
Date: Wed Nov 24 02:59:42 UTC 2021
Last-known Working: Unknown

### System Information

Field | Value
-- | --
OS | Ubuntu 20.04.3 LTS
CPU | Intel(R) Pentium(R) CPU 3825U @ 1.90GHz
Graphics Device | Mesa Intel(R) HD Graphics (BDW GT1)
Graphics Driver | Drivers: 4.6 (Core Profile) Mesa 21.0.3

### Additional Context

Star Wars The Clone Wars and Lakemasters Bass Fishing Game have matching behavior but with Lakemasters it only affect the letter o

**Comment by MasonT8198** [comment]
Looks like a half pixel offset issue

**Comment by Triticum0** [comment]
This is probably fixed by  #735 from testing

**Comment by Triticum0** [comment]
#735 fixes 
- [Dynasty Warriors3](https://xemu.app/titles/4b4f0003/#Dynasty-Warriors-3) partially still broken when upscaled 
- [Buffy the Vampire Slayer Chaos Bleeds](https://xemu.app/titles/56550005/#Buffy-the-Vampire-Slayer-Chaos-Bleeds)

**Comment by SonOfKorriban** [comment]
I can confirm, that this issue is still there for Star Wars: The Clone Wars. Any Workaround?

**Comment by Langerz82** [comment]
Confirm the issue is still present in Rallisport Challenge:
![image](https://github.com/user-attachments/assets/0671757d-367a-4c28-91e0-e1da1dd815d3)
In the bottom text some of the glyphs get cut off on the top-left side.

**Comment by Triticum0** [comment]
This has been fixed at 1x resolution

**Comment by Langerz82** [comment]
@Triticum0 Confirmed fixed as of v0.8.66 at 1x. It only clips if it's set to stretch to window or higher than 1x. Keep up the good work!! 

Tested in Rallisport Challenge.

**Comment by Deadliestbridge** [comment]
Star Wars Obi-Wan Is also having text offset problems that were not present in previous versions as of 0.8.75 at 1x

![Image](https://github.com/user-attachments/assets/2617e5d8-e674-44ee-9424-63199723295b)

![Image](https://github.com/user-attachments/assets/8b15ac1a-1e08-406a-b52a-0302f4fefc07)

**Comment by Deadliestbridge** [comment]
Text seems fixed The Clone Wars in native res

![Image](https://github.com/user-attachments/assets/f8313f16-2f5e-4ed5-bacb-fb319acca676)

![Image](https://github.com/user-attachments/assets/9016486b-76cd-4807-9f02-be6338ad7424)

![Image](https://github.com/user-attachments/assets/803cbee5-59ca-4a92-8ea4-3f049476aeaf)
