### ISSUE TITLE
Crash Twinsanity Game Screen Spazzes out - M1 macOS

### ISSUE THREAD

**Issue by B00MST3R** [xemu-project/xemu#658]
### Bug Description

The Game Screen on Crash Twinsanity constantly does this error when playing it.
<img width="1136" alt="Screen Shot 2022-01-17 at 8 09 02 pm" src="https://user-images.githubusercontent.com/27199101/149749991-c4642a0b-ba39-47a0-af8f-aaa446e4bd9a.png">
 

### Expected Behavior

It says playable on the main menu, just thought it should be working?

### xemu Version

<img width="1136" alt="Screen Shot 2022-01-17 at 8 09 02 pm" src="https://user-images.githubusercontent.com/27199101/149750134-83c78fb6-5b8c-4c9c-a2f2-09830c656c52.png">
That's the latest up to date version i have on the Mac

### System Information

OS: Mac Os Monterey

Graphics: M1 Chip

Edit: If someone can help me fix this or if this is a bug, just wanting to help out the emulation team.

**Comment by Triticum0** [comment]
This was fixed for other GPU that not mac back in June #319 don't know why it broken for mac though.

**Comment by B00MST3R** [comment]
Sorry, I got a little confused what you meant there? Is it fixed for Windows but not for Macbook do you mean?

**Comment by Triticum0** [comment]
Yes, it fixed on window and Linux but not mac by the looks of it.

**Comment by B00MST3R** [comment]
I see, thanks for the update, hopefully they'll fix it so I can fully play this and enjoy it like old times.

**Comment by B00MST3R** [comment]
Still a note, this still doesn't completely work when playing Crash Twinsanity, The Audio still plays as usual then it just really goes gobbly goop on the screen. Just updating.

**Comment by abaire** [comment]
Would be good to retest with a recent xemu release to see if this still occurs on Apple silicon/macOS

**Comment by Triticum0** [comment]
Also occurs on Steam deck and Intel Gpus.

**Comment by Triticum0** [comment]
I retest on Intel 5th gen integrated Gpu and couldn't reproduce https://github.com/xemu-project/xemu/issues/1371#issuecomment-1830779445 said it occurs on Intel UHD Graphics for 8th Generation Intel so think this probably fixed. @B00MST3R Retest.
